// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfdg4Dij6CyGsSQTNKnDC_US7CFS6H67g',
    appId: '1:670573932776:web:7d393fe5387caa2c95d95d',
    messagingSenderId: '670573932776',
    projectId: 'doctorapp-f2422',
    authDomain: 'doctorapp-f2422.firebaseapp.com',
    storageBucket: 'doctorapp-f2422.firebasestorage.app',
    measurementId: 'G-S9BYVPM35W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK466CXBUXb8FI-j2d9TglKqIpKTDfrwE',
    appId: '1:670573932776:android:6827fda019a6389e95d95d',
    messagingSenderId: '670573932776',
    projectId: 'doctorapp-f2422',
    storageBucket: 'doctorapp-f2422.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4gPh4QzXBvY2QCmlSWN2EG532jmokMh8',
    appId: '1:670573932776:ios:9910e5f4d5b6c35e95d95d',
    messagingSenderId: '670573932776',
    projectId: 'doctorapp-f2422',
    storageBucket: 'doctorapp-f2422.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentApp',
  );
}
